/*
 * This class is used to show all movies present in databse as a list view.
 */
package xtra.vision;

import java.awt.Component;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ha349
 */
public class MoviesListView extends javax.swing.JPanel {

    /**
     * Creates new form MoviesListView
     */
    public MoviesListView(ArrayList List) {
        this.list = List;
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(800, 540));
        setMinimumSize(new java.awt.Dimension(800, 540));
        setPreferredSize(new java.awt.Dimension(800, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        this.addList();
        jScrollPane1.setViewportView(jPanel2);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));
    }// </editor-fold>//GEN-END:initComponents
  /*
 * This function gets the list of movies and show it on screen.
 */
    public void addList(){
    for(int i=0; i < list.size();i++){
        Movie a = (Movie)list.get(i);
        try {                
        BufferedImage poster = ImageIO.read(this.getClass().getResource("posters/"+a.getName()+".jpg"));
        JLabel title = new JLabel(a.getName(),JLabel.CENTER);        
        title.setIcon(new ImageIcon(poster));
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
               Component source=(Component)evt.getSource();
                source.getParent().dispatchEvent(evt);
            }
        });
        jPanel2.add(title);
        
       } catch (IOException ex) {
            // handle exception...
       }
    }
}
public void addMouseListener(MouseListener listener){
    this.jPanel2.addMouseListener(listener);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private ArrayList list; 
}
