/*
 * This class is used to show payment details to user.
 */
package xtra.vision;

import java.awt.event.ActionListener;

/**
 *
 * @author ha349
 */
public class PaymentView extends javax.swing.JPanel {

    /**
     * Creates new form MovieDetailView
     */
    public PaymentView() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cardNum = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(800, 540));
        setMinimumSize(new java.awt.Dimension(800, 540));
        setPreferredSize(new java.awt.Dimension(800, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Debit/Credit Card Details");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 160, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Cancel");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 110, 20));

        email.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 400, -1));

        jLabel2.setText("Card Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        jLabel3.setText("Email Address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Pay Now");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText(String.valueOf(RentGUI.cart.calculateAndReturnPrice()));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("You will be charged");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 120, 20));

        try {
            cardNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(cardNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 400, -1));

        jLabel6.setText("Enter 16 digit card number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, 20));
    }// </editor-fold>//GEN-END:initComponents
    public void addPayButtListener(ActionListener listener){
        this.jButton3.addActionListener(listener);        
    }

    public void addCancelButtListener(ActionListener listener){
        this.jButton1.addActionListener(listener);        
    }
    
    public String[] getEmailAndCardNo(){
        String data[] = new String[2];        
        data[0] = email.getText();
        data[1] = cardNum.getText();
        return data;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cardNum;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
   public static final String EMAIL_PATTERN = 
    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
}
