/*
 * This class is used to show the results of renting the movie.
 */
package xtra.vision;

import java.awt.event.ActionListener;

/**
 *
 * @author ha349
 */
public class RentFinalView extends javax.swing.JPanel {

    /**
     * Creates new form MovieDetailView
     */
    public RentFinalView() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(800, 540));
        setMinimumSize(new java.awt.Dimension(800, 540));
        setPreferredSize(new java.awt.Dimension(800, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Transaction Successful");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, -1));
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 110, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("You can take away your discs Now....");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 710, -1));

        jButton2.setText("Exit");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 90, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void addExitButtListener(ActionListener listener){
        this.jButton2.addActionListener(listener);        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
   
}
