/*
 * This class is used to show the interface for getting user input for returning the movie.
 */
package xtra.vision;

import java.awt.event.ActionListener;

/**
 *
 * @author ha349
 */
public class ReturnView extends javax.swing.JPanel {

    /**
     * Creates new form MovieDetailView
     */
    public ReturnView() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tagNo = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(800, 540));
        setMinimumSize(new java.awt.Dimension(800, 540));
        setPreferredSize(new java.awt.Dimension(800, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Enter movie Electronic Tag Number present at back of your disc");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 390, -1));
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 110, 20));

        jLabel2.setText("Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Return");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        try {
            tagNo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(tagNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 400, -1));

        jLabel6.setText("Enter 6 digit Tag number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, 20));
    }// </editor-fold>//GEN-END:initComponents
    public void addReturnButtListener(ActionListener listener){
        this.jButton3.addActionListener(listener);        
    }
    public String getMovieName(){
        return tagNo.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField tagNo;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

}
